
services:

  postgres:
    image: postgres:16.3-alpine
    container_name: postgres-container
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-ms-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ecommerce-ms-network

  user-api:
    image: shop/user-api:latest
    container_name: user-api-container
    ports:
      - "8081:8081"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb-development
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      SHOW_SQL: true
    depends_on:
      - postgres
    networks:
      - ecommerce-ms-network

  product-api:
    image: shop/product-api:latest
    container_name: product-api-container
    ports:
      - "8082:8082"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/productdb-development
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      SHOW_SQL: true
    depends_on:
      - postgres
    networks:
      - ecommerce-ms-network

  shop-api:
    image: shop/shop-api:latest
    container_name: shop-api-container
    ports:
      - "8083:8083"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopdb-devlopment
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      SERVICE_USER_API_URL: http://user-api:8081
      SERVICE_PRODUCT_API_URL: http://product-api:8082
      SHOW_SQL: true
    depends_on:
      - postgres
    networks:
      - ecommerce-ms-network

volumes:
  postgres_data:

networks:
  ecommerce-ms-network:
    driver: bridge
