
services:

  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shopping-ms-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - shopping-ms-network

  user-api:
    image: user-api:latest
    container_name: user-api
    ports:
      - "8081:8081"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/user-dev
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      SHOW_SQL: true
    depends_on:
      - postgres
    networks:
      - shopping-ms-network

  product-api:
    image: product-api:latest
    container_name: product
    ports:
      - "8082:8082"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/product-dev
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      SHOW_SQL: true
    depends_on:
      - postgres
    networks:
      - shopping-ms-network

  shop-api:
    image: shop-api:latest
    container_name: shop-api
    ports:
      - "8083:8083"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/shop-dev
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      SERVICE_USER_API_URL: http://user-api:8081
      SERVICE_PRODUCT_API_URL: http://product-api:8082
      SHOW_SQL: true
    depends_on:
      - postgres
    networks:
      - shopping-ms-network

volumes:
  postgres_data:

networks:
  shopping-ms-network:
    driver: bridge
