apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-api-deploy
  namespace: shopping
  labels:
    app: shop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-api
  template:
    metadata:
      labels:
        app: shop-api
    spec:
      containers:
        - name: shop-api
          image: shop-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
              name: http
          envFrom:
            - configMapRef:
                name: shop-api-configmap
            - secretRef:
                name: shop-api-secret
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8081
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8081
          #   initialDelaySeconds: 60
          #   periodSeconds: 10

