apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-api-configmap
  namespace: shopping
data:
  SERVER_PORT: "8083"
  DATASOURCE_CONNECTION_TIMEOUT: "20000"
  DATASOURCE_MAX_POOL_SIZE: "5"
  DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/shop-stage"
  DATASOURCE_USERNAME: "postgres"
  SERVICE_USER_API_URL: http://user-api:8081
  SERVICE_PRODUCT_API_URL: http://product-api:8082
  SHOW_SQL: "true"
  FORMAT_SQL: "true"
