apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: user-api
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.service: user-api
    spec:
      containers:
        - env:
            - name: DATASOURCE_PASSWORD
              value: postgres
            - name: DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/userdb-development
            - name: DATASOURCE_USERNAME
              value: postgres
            - name: SHOW_SQL
              value: "true"
          image: shop/user-api:latest
          imagePullPolicy: Never
          name: user-api
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
