apiVersion: v1
kind: ConfigMap
metadata:
  name: product-api-configmap
  namespace: shopping
data:
  SERVER_PORT: "8082"
  DATASOURCE_CONNECTION_TIMEOUT: "20000"
  DATASOURCE_MAX_POOL_SIZE: "5"
  DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/productdb-development"
  DATASOURCE_USERNAME: "postgres"
  SHOW_SQL: "true"
  FORMAT_SQL: "true"