apiVersion: v1
kind: ConfigMap
metadata:
  name: user-api-configmap
  namespace: shopping
data:
  SERVER_PORT: "8081"
  DATASOURCE_CONNECTION_TIMEOUT: "20000"
  DATASOURCE_MAX_POOL_SIZE: "5"
  DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/user-stage"
  DATASOURCE_USERNAME: "postgres"
  SHOW_SQL: "true"
  FORMAT_SQL: "true"
